# Generated by Django 2.0 on 2020-12-15 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDataModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, unique=True)),
                ('phoneNumber', models.CharField(max_length=11, unique=True)),
                ('userPassword', models.CharField(max_length=10)),
                ('useremail', models.EmailField(max_length=254, null=True)),
                ('shop', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'userdata',
            },
        ),
        migrations.CreateModel(
            name='UserDataModelsContext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signatureText', models.TextField(default='大家好')),
                ('portraitImage', models.ImageField(default='UserPortrait/用户.png', null=True, upload_to='UserPortrait')),
                ('UserObject', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usercontent', to='UserData.UserDataModels')),
            ],
            options={
                'db_table': 'userContext',
            },
        ),
        migrations.CreateModel(
            name='UserShop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopName', models.CharField(max_length=255)),
                ('shopPrice', models.IntegerField()),
                ('shopQuantity', models.IntegerField()),
                ('shopImage', models.ImageField(null=True, upload_to='shopImages')),
                ('monthlySales', models.IntegerField(default=0, null=True)),
                ('salesQuantity', models.IntegerField(default=0, null=True)),
                ('shopUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserData.UserDataModels')),
            ],
            options={
                'db_table': 'userShop',
            },
        ),
    ]
