# Generated by Django 3.0.4 on 2020-10-21 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDataModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('phoneNumber', models.CharField(max_length=11)),
                ('userPassword', models.CharField(max_length=10)),
                ('useremail', models.EmailField(max_length=254, null=True)),
            ],
            options={
                'db_table': 'userdata',
            },
        ),
        migrations.CreateModel(
            name='UserDataModelsContext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signatureText', models.TextField(default='大家好')),
                ('portraitImage', models.ImageField(default='UserPortrait/用户.png', null=True, upload_to='UserPortrait')),
                ('UserObject', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='UserData.UserDataModels')),
            ],
            options={
                'db_table': 'userContext',
            },
        ),
        migrations.CreateModel(
            name='DemoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demo', to='UserData.UserDataModels')),
            ],
        ),
    ]
