# Generated by Django 3.0.4 on 2020-10-21 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserData', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdatamodels',
            name='phoneNumber',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='userdatamodels',
            name='useremail',
            field=models.EmailField(default='', max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userdatamodels',
            name='username',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.DeleteModel(
            name='DemoModel',
        ),
    ]
