# Generated by Django 3.0.4 on 2020-10-22 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserData', '0002_auto_20201022_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdatamodels',
            name='useremail',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
