# Generated by Django 3.0.4 on 2020-11-15 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserData', '0004_auto_20201026_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdatamodels',
            name='shop',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userdatamodelscontext',
            name='UserObject',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usercontent', to='UserData.UserDataModels'),
        ),
    ]
