# Generated by Django 3.0.4 on 2020-11-15 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserData', '0005_auto_20201115_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserShop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopName', models.CharField(max_length=255)),
                ('shopPrice', models.IntegerField()),
                ('shopQuantity', models.IntegerField()),
                ('monthlySales', models.IntegerField()),
                ('salesQuantity', models.IntegerField()),
                ('shopUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserData.UserDataModels')),
            ],
        ),
    ]
