# Generated by Django 3.0.4 on 2020-11-15 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserData', '0006_usershop'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usershop',
            table='userShop',
        ),
    ]
