# Generated by Django 3.0.4 on 2020-11-18 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserData', '0008_usershop_shopimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usershop',
            name='monthlySales',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='usershop',
            name='salesQuantity',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
